sudo: false
language: java
install: true

jdk: openjdk8

git:
  depth: 500
addons:
  sonarcloud:
    organization: rajasekarangss
    token:
      secure: 32e73367defb97fb9a7304f04a0469ea7fb5abd5

# before_install:
# - chmod +x mvnw

script:
# - "./mvnw clean install -B"
# - "./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar"
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
# - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report
# - if [ "$JAVA_HOME" = "/usr/lib/jvm/java-1.8.0-openjdk-amd64" ]; then mvn sonar:sonar; fi

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
